import { ApiProperty } from '@nestjs/swagger';
import type { CatalogProductSize, CatalogProductType } from '../domain/catalog.types';
import type { ProductDto, ProductVariantDto } from './catalog-products.controller.dto.types';
export class ProductVariantRequestDto { @ApiProperty({ enum: ['S', 'M', 'L'] }) size!: CatalogProductSize; @ApiProperty({ format: 'int32', type: 'integer', minimum: 0 }) priceMinor!: number; @ApiProperty({ format: 'int32', type: 'integer', minimum: 0 }) sortOrder!: number; @ApiProperty() isAvailable!: boolean; }
export class CreateProductDto { @ApiProperty({ format: 'uuid' }) categoryId!: string; @ApiProperty({ enum: ['DRINK', 'OTHER'] }) type!: CatalogProductType; @ApiProperty() name!: string; @ApiProperty() description!: string; @ApiProperty({ format: 'int32', type: 'integer', nullable: true }) priceMinor!: number | null; @ApiProperty({ format: 'int32', type: 'integer', minimum: 0 }) sortOrder!: number; @ApiProperty() isActive!: boolean; @ApiProperty() isAvailable!: boolean; @ApiProperty({ type: () => ProductVariantRequestDto, isArray: true }) variants!: ProductVariantRequestDto[]; }
export class UpdateProductDto extends CreateProductDto {}
export class ReorderProductsDto { @ApiProperty({ format: 'uuid' }) categoryId!: string; @ApiProperty({ type: 'string', format: 'uuid', isArray: true }) productIds!: string[]; }
export class ProductVariantResponseDto implements ProductVariantDto { @ApiProperty({ format: 'uuid' }) id!: string; @ApiProperty({ enum: ['S', 'M', 'L'] }) size!: CatalogProductSize; @ApiProperty({ format: 'int32', type: 'integer' }) priceMinor!: number; @ApiProperty({ format: 'int32', type: 'integer' }) sortOrder!: number; @ApiProperty() isAvailable!: boolean; }
export class ProductResponseDto implements ProductDto { @ApiProperty({ format: 'uuid' }) id!: string; @ApiProperty({ format: 'uuid' }) categoryId!: string; @ApiProperty({ enum: ['DRINK', 'OTHER'] }) type!: CatalogProductType; @ApiProperty() name!: string; @ApiProperty() description!: string; @ApiProperty({ format: 'int32', type: 'integer', nullable: true }) priceMinor!: number | null; @ApiProperty({ format: 'int32', type: 'integer' }) sortOrder!: number; @ApiProperty() isActive!: boolean; @ApiProperty() isAvailable!: boolean; @ApiProperty({ type: () => ProductVariantResponseDto, isArray: true }) variants!: ProductVariantResponseDto[]; }
