// Canonical back-office theme values. Feature code consumes semantic CSS tokens.
export const expressaAdminThemeColors = {
  background: "#FFFFFF",
  surface: "#FFFFFF",
  "surface-raised": "#F6F7F9",
  "surface-subtle": "#EEF0F4",
  primary: "#2635FF",
  "primary-hover": "#1D29D9",
  "primary-active": "#151EAD",
  secondary: "#F6F7F9",
  success: "#187A48",
  warning: "#5B6068",
  error: "#C62828",
  info: "#2635FF",
  "on-background": "#17181A",
  "on-surface": "#17181A",
  "on-primary": "#FFFFFF",
  "on-secondary": "#17181A",
  "on-success": "#FFFFFF",
  "on-warning": "#FFFFFF",
  "on-error": "#FFFFFF",
  "on-info": "#FFFFFF",
  "text-primary": "#17181A",
  "text-secondary": "#5B6068",
  "text-muted": "#8A9099",
  "border-default": "#D7DAE0",
  "border-strong": "#AEB4BE",
  "status-success": "#187A48",
  "status-success-surface": "#ECF8F1",
  "status-warning": "#5B6068",
  "status-warning-surface": "#EEF0F4",
  "status-error": "#C62828",
  "status-error-surface": "#FFF1F1",
  "status-neutral": "#5B6068",
  "status-neutral-surface": "#EEF0F4",
  "status-info-surface": "#EEF0FF",
} as const;
