// Canonical Admin color values for Vuetify; CSS consumes Vuetify theme variables.
export const expressaAdminThemeColors = {
  background: "#FFFFFF",
  surface: "#FFFFFF",
  "surface-raised": "#F5F5F7",
  primary: "#1A1AFF",
  secondary: "#F5F5F7",
  success: "#2E7D32",
  warning: "#E65100",
  error: "#D32F2F",
  info: "#1A1AFF",
  "on-background": "#111111",
  "on-surface": "#111111",
  "on-primary": "#FFFFFF",
  "on-secondary": "#111111",
  "on-success": "#FFFFFF",
  "on-warning": "#FFFFFF",
  "on-error": "#FFFFFF",
  "on-info": "#FFFFFF",
  "text-primary": "#111111",
  "text-secondary": "#555555",
  "text-muted": "#999999",
  "border-default": "#E0E0E0",
  "border-strong": "#BDBDBD",
  "status-success": "#2E7D32",
  "status-success-surface": "#E8F5E9",
  "status-warning": "#C54500",
  "status-warning-surface": "#FFF3E0",
  "status-error": "#CE2E2E",
  "status-error-surface": "#FFEBEE",
  "status-neutral": "#707070",
  "status-neutral-surface": "#F5F5F5",
  "status-info-surface": "#E8E8FF",
} as const;
