import type { Meta, StoryObj } from "@storybook/vue3-vite";

const semantic = [
  "--customer-color-brand",
  "--customer-color-brand-raised",
  "--customer-color-action-primary",
  "--customer-color-surface",
  "--customer-color-surface-subtle",
  "--customer-color-text-on-brand",
  "--customer-color-text-on-surface",
  "--customer-color-text-muted-on-brand",
  "--customer-color-text-muted-on-surface",
  "--customer-color-border-on-brand",
  "--customer-color-focus",
  "--customer-surface-control",
  "--customer-surface-muted",
  "--customer-surface-muted-on-brand",
  "--customer-surface-note",
  "--customer-surface-sidebar",
  "--customer-surface-info",
  "--customer-border-subtle-on-brand",
  "--customer-border-subtle-on-surface",
  "--customer-text-subtle-on-brand",
  "--customer-text-secondary-on-brand",
  "--customer-text-tertiary-on-brand",
  "--customer-text-faint-on-brand",
  "--customer-text-strong-on-brand",
  "--customer-text-danger",
  "--customer-surface-danger",
  "--customer-background",
  "--customer-background-raised",
  "--customer-surface",
  "--customer-text",
  "--customer-text-on-surface",
  "--customer-primary",
  "--customer-success",
  "--customer-error",
  "--customer-danger",
  "--customer-danger-10",
  "--customer-danger-pale",
  "--customer-border",
  "--customer-focus-ring",
];
const raw = [
  "--customer-color-blue-700",
  "--customer-color-blue-600",
  "--customer-color-blue-500",
  "--customer-color-orange-500",
  "--customer-color-white",
  "--customer-color-black",
  "--customer-color-success",
  "--customer-color-danger",
  "--customer-color-error",
  "--customer-color-danger-light",
  "--customer-color-danger-pale",
  "--customer-color-warning",
  "--customer-color-warning-surface",
  "--customer-color-info-surface",
  "--customer-color-success-surface",
  "--customer-color-white-70",
  "--customer-color-white-65",
  "--customer-color-white-60",
  "--customer-color-white-50",
  "--customer-color-white-45",
  "--customer-color-white-35",
  "--customer-color-white-30",
  "--customer-color-white-25",
  "--customer-color-white-22",
  "--customer-color-white-18",
  "--customer-color-white-15",
  "--customer-color-white-13",
  "--customer-color-white-12",
  "--customer-color-white-10",
  "--customer-color-white-9",
  "--customer-color-white-8",
  "--customer-color-white-82",
  "--customer-color-white-85",
  "--customer-color-blue-500-15",
  "--customer-color-blue-500-10",
  "--customer-color-blue-500-4",
  "--customer-color-blue-700-60",
  "--customer-color-blue-700-55",
  "--customer-color-blue-700-50",
  "--customer-color-blue-700-45",
  "--customer-color-blue-700-8",
  "--customer-color-danger-30",
  "--customer-color-danger-15",
  "--customer-color-danger-10",
  "--customer-color-orange-500-65",
  "--customer-color-black-35",
  "--customer-color-black-18",
  "--customer-color-black-15",
  "--customer-color-black-14",
  "--customer-color-black-12",
  "--customer-color-black-10",
  "--customer-color-brand",
  "--customer-color-brand-raised",
  "--customer-color-action-primary",
  "--customer-color-surface",
  "--customer-color-surface-subtle",
  "--customer-color-text-on-brand",
  "--customer-color-text-on-surface",
  "--customer-color-text-muted-on-brand",
  "--customer-color-text-muted-on-surface",
  "--customer-color-border-on-brand",
  "--customer-color-focus",
];

const meta = {
  title: "Foundation/Colors",
  tags: ["autodocs"],
  argTypes: {},
  parameters: {
    layout: "centered",
    docs: {
      description: {
        component:
          "Палитра Customer из `src/styles/customer-tokens.css`. Верхний ряд — все semantic surface/text/border/danger aliases и public semantic values; таблица — все primitive/raw and compatibility color tokens. Значения и aliases принадлежат token authority; consumer выбирает semantic token и проверяет contrast. Static specimen: props, emits, slots, actions и states отсутствуют.",
      },
    },
  },
} satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;
export const Palette: Story = {
  render: () => ({
    data: () => ({ raw, semantic }),
    template: `<div style="display:grid;gap:var(--customer-space-9);width:100%;max-width:56rem;font-family:var(--customer-font-family)"><section><h2 style="margin:0 0 var(--customer-space-5)">Semantic specimens</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(10rem,1fr));gap:var(--customer-space-5)"><div v-for="token in semantic" :key="token"><div :style="{height:'3rem',background:'var('+token+')',border:'1px solid var(--customer-color-black-18)',borderRadius:'var(--customer-radius-sm)'}"></div><code style="overflow-wrap:anywhere">{{ token }}</code></div></div></section><section style="overflow-x:auto"><h2 style="margin:0 0 var(--customer-space-5)">Raw and compatibility tokens</h2><table style="width:100%;border-collapse:collapse"><tbody><tr v-for="token in raw" :key="token"><td style="padding:var(--customer-space-3);border-bottom:1px solid var(--customer-color-black-12)"><code>{{ token }}</code></td><td style="padding:var(--customer-space-3);border-bottom:1px solid var(--customer-color-black-12)"><span :style="{display:'inline-block',width:'2rem',height:'1rem',background:'var('+token+')',border:'1px solid var(--customer-color-black-18)'}"></span></td></tr></tbody></table></section></div>`,
  }),
};
