import { ManageModifiersUseCase } from './manage-modifiers.use-case';
import type { ModifiersRepository, ModifiersUnitOfWork } from './modifiers.repository.types';
const group = { id: 'group', name: 'Молоко', selectionType: 'multiple' as const, minSelect: 1, maxSelect: 2, isActive: true, archivedAt: null, options: [] };
const option = { id: 'option', groupId: group.id, name: 'Овсяное', priceDelta: 0, sortOrder: 0, isDefault: true, isAvailable: true, archivedAt: null };
function setup() { const repository: jest.Mocked<ModifiersRepository> = { findGroupById: jest.fn(), findOptionById: jest.fn(), findCurrentOptionsByGroup: jest.fn(), createGroup: jest.fn(), updateGroup: jest.fn(), archiveGroup: jest.fn(), createOption: jest.fn(), updateOption: jest.fn(), reorderOptions: jest.fn(), archiveOption: jest.fn(), writeAudit: jest.fn() }; const unitOfWork: ModifiersUnitOfWork = { run: async (command, audit) => { const result = await command(repository); await audit(repository, result); return result; } }; return { repository, useCase: new ManageModifiersUseCase(unitOfWork) }; }
describe('ManageModifiersUseCase', () => {
  it('сохраняет обязательную группу и defaults единым aggregate', async () => { const { repository, useCase } = setup(); repository.createGroup.mockResolvedValue({ ...group, options: [option] }); await expect(useCase.createGroup({ ...group, options: [{ name: option.name, priceDelta: 0, sortOrder: 0, isDefault: true, isAvailable: true }], actorId: 'actor', requestId: 'request' })).resolves.toMatchObject({ options: [expect.objectContaining({ id: option.id })] }); expect(repository.createGroup).toHaveBeenCalledWith(expect.objectContaining({ name: group.name }), [expect.objectContaining({ name: option.name })]); expect(repository.writeAudit).toHaveBeenCalledWith(expect.objectContaining({ before: null, after: expect.objectContaining({ options: [expect.any(Object)] }) })); });
  it('возвращает путь ошибочного варианта до записи', async () => { const { repository, useCase } = setup(); await expect(useCase.createGroup({ ...group, options: [{ name: '', priceDelta: 0, sortOrder: 0, isDefault: true, isAvailable: true }], actorId: 'actor', requestId: 'request' })).rejects.toMatchObject({ code: 'MODIFIER_INVALID', fields: [expect.objectContaining({ path: 'options.0.name' })] }); expect(repository.createGroup).not.toHaveBeenCalled(); });
  it('создаёт, изменяет и архивирует группу с точным аудитом', async () => {
    const { repository, useCase } = setup(); const optional = { ...group, minSelect: 0 };
    repository.createGroup.mockResolvedValue(optional); repository.findGroupById.mockResolvedValue(optional); repository.findCurrentOptionsByGroup.mockResolvedValue([option]); repository.updateGroup.mockResolvedValue({ ...optional, name: 'Сироп' }); repository.archiveGroup.mockResolvedValue({ ...optional, archivedAt: new Date('2026-08-04T00:00:00.000Z') });
    await expect(useCase.createGroup({ ...optional, actorId: 'actor', requestId: 'request' })).resolves.toEqual(optional);
    await expect(useCase.updateGroup({ ...optional, name: 'Сироп', groupId: optional.id, actorId: 'actor', requestId: 'request' })).resolves.toMatchObject({ name: 'Сироп' });
    await expect(useCase.archiveGroup({ groupId: optional.id, actorId: 'actor', requestId: 'request' })).resolves.toBeUndefined();
    expect(repository.writeAudit).toHaveBeenNthCalledWith(1, expect.objectContaining({ action: 'MODIFIER_GROUP_CREATED', before: null, after: optional }));
    expect(repository.writeAudit).toHaveBeenNthCalledWith(2, expect.objectContaining({ action: 'MODIFIER_GROUP_UPDATED', before: optional, after: expect.objectContaining({ name: 'Сироп' }) }));
    expect(repository.writeAudit).toHaveBeenNthCalledWith(3, expect.objectContaining({ action: 'MODIFIER_GROUP_ARCHIVED', before: optional, after: expect.objectContaining({ archivedAt: expect.any(Date) }) }));
  });
  it('создаёт вариант с атомарным аудитом', async () => { const { repository, useCase } = setup(); repository.findGroupById.mockResolvedValue(group); repository.findCurrentOptionsByGroup.mockResolvedValue([]); repository.createOption.mockResolvedValue(option); await expect(useCase.createOption({ ...option, groupId: group.id, actorId: 'actor', requestId: 'request' })).resolves.toEqual(option); expect(repository.writeAudit).toHaveBeenCalledWith(expect.objectContaining({ action: 'MODIFIER_OPTION_CREATED', before: null, after: option })); });
  it('не архивирует default, нарушающий обязательную группу', async () => { const { repository, useCase } = setup(); repository.findOptionById.mockResolvedValue(option); repository.findGroupById.mockResolvedValue(group); repository.findCurrentOptionsByGroup.mockResolvedValue([option]); await expect(useCase.archiveOption({ optionId: option.id, actorId: 'actor', requestId: 'request' })).rejects.toThrow('MODIFIER_INVALID'); expect(repository.archiveOption).not.toHaveBeenCalled(); });
  it('изменяет, переупорядочивает и архивирует варианты с точным аудитом', async () => {
    const { repository, useCase } = setup(); const optional = { ...group, minSelect: 0 }; const second = { ...option, id: 'option-2', sortOrder: 1 };
    repository.findOptionById.mockResolvedValueOnce(option).mockResolvedValueOnce(option); repository.findGroupById.mockResolvedValue(optional); repository.findCurrentOptionsByGroup.mockResolvedValueOnce([option, second]).mockResolvedValueOnce([option, second]).mockResolvedValueOnce([option, second]); repository.updateOption.mockResolvedValue({ ...option, name: 'Кокосовое' }); repository.reorderOptions.mockResolvedValue([second, option]); repository.archiveOption.mockResolvedValue({ ...option, archivedAt: new Date('2026-08-04T00:00:00.000Z') });
    await expect(useCase.updateOption({ ...option, name: 'Кокосовое', optionId: option.id, actorId: 'actor', requestId: 'request' })).resolves.toMatchObject({ name: 'Кокосовое' });
    await expect(useCase.reorderOptions({ groupId: optional.id, optionIds: [second.id, option.id], actorId: 'actor', requestId: 'request' })).resolves.toEqual([second, option]);
    await expect(useCase.archiveOption({ optionId: option.id, actorId: 'actor', requestId: 'request' })).resolves.toBeUndefined();
    expect(repository.writeAudit).toHaveBeenNthCalledWith(1, expect.objectContaining({ action: 'MODIFIER_OPTION_UPDATED', before: option, after: expect.objectContaining({ name: 'Кокосовое' }) }));
    expect(repository.writeAudit).toHaveBeenNthCalledWith(2, expect.objectContaining({ action: 'MODIFIER_OPTION_REORDERED', entityId: second.id, before: second, after: second }));
    expect(repository.writeAudit).toHaveBeenNthCalledWith(3, expect.objectContaining({ action: 'MODIFIER_OPTION_REORDERED', entityId: option.id, before: option, after: option }));
    expect(repository.writeAudit).toHaveBeenNthCalledWith(4, expect.objectContaining({ action: 'MODIFIER_OPTION_ARCHIVED', before: option, after: expect.objectContaining({ archivedAt: expect.any(Date) }) }));
  });
  it('отклоняет archive отсутствующей группы и неполный reorder до записи', async () => { const { repository, useCase } = setup(); repository.findGroupById.mockResolvedValue(null); await expect(useCase.archiveGroup({ groupId: group.id, actorId: 'actor', requestId: 'request' })).rejects.toThrow('MODIFIER_GROUP_NOT_FOUND'); repository.findGroupById.mockResolvedValue({ ...group, minSelect: 0 }); repository.findCurrentOptionsByGroup.mockResolvedValue([option]); await expect(useCase.reorderOptions({ groupId: group.id, optionIds: [], actorId: 'actor', requestId: 'request' })).rejects.toThrow('MODIFIER_REORDER_INVALID'); expect(repository.reorderOptions).not.toHaveBeenCalled(); });
});
