name: Back-office delivery

on:
  push:
    tags: ['back-office-v*']

permissions:
  contents: read

jobs:
  deliver:
    uses: ./.github/workflows/delivery-component.yml
    with:
      component: back-office
      context: back-office
      image: expressa-back-office
      deployment_environment: development
    secrets:
      EXPRESSA_VPS_HOST: ${{ secrets.EXPRESSA_VPS_HOST }}
      EXPRESSA_VPS_PORT: ${{ secrets.EXPRESSA_VPS_PORT }}
      EXPRESSA_VPS_DEPLOY_USER: ${{ secrets.EXPRESSA_VPS_DEPLOY_USER }}
      EXPRESSA_VPS_DEPLOY_SSH_KEY: ${{ secrets.EXPRESSA_VPS_DEPLOY_SSH_KEY }}
      EXPRESSA_VPS_KNOWN_HOSTS: ${{ secrets.EXPRESSA_VPS_KNOWN_HOSTS }}
